language: android
android:
components:
    - build-tools-21.1.2
    - android-19
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
    - add-on
    - extra

before_script:
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator 
