language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-27.0.3
    - android-28
    
  licenses:
    - "android-sdk-license-.+"
    - "google-gdk-license-.+"
    - yes | sdkmanager "build-tools;27.0.3"
    - yes | sdkmanager "platforms;android-28"

before_script:
    - chmod +x gradlew
    
script:
  - "./gradlew assemblerelease"
  - "./gradlew clean"
